version: '3.4'

services:
  catalogdb:
    image: postgres
    build:
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  basketdb:
    image: postgres
    build:
      dockerfile: Services/Basket/Basket.API/Dockerfile
  distributedcache:
    image: redis
    build:
      dockerfile: Services/Basket/Basket.API/Dockerfile
  orderdb:
    image: mcr.microsoft.com/mssql/server
  messagebroker:
    image: rabbitmq:management
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Disccount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  shopping.web:
    image: ${DOCKER_REGISTRY-}shoppingweb
    build:
      context: .
      dockerfile: WebApps/Shopping.Web/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:






